### ISSUE TITLE
Failed Delay

### ISSUE THREAD

**Issue by mesutgungor** [arael/moodle_notifications_20#16]
Hi Areal ,
Notification block was working for nearly 2 months perfectly but it eventually stopped working. it always gives failed delay in scheduled task window. What can be the problem ? What does the parameter Notified events history length ? Can this be the cause of this issue ? It was set to 1000 
Thanks.

**Comment by arael** [comment]
That should not be a problem but it is a high number indeed. Anyway have you tried to check the server logs. There probably are some errors prompted there.

**Comment by mesutgungor** [comment]
her is the apache error log file related with notifications block. 
But this does not give a clue to solve. 
./httpd/error_log-20150222:[Sun Feb 22 02:34:44 2015] [error] [client 65.19.138.33] File does not exist: /var/www/html/blocks/notifications/lib
Do you have an advice to do ?
When i run the cron script through cli and also through web i cannot see the lines related with the notifications block. How can i make it appear in those verbose log.

**Comment by arael** [comment]
What version of the block are you running?

**Comment by mesutgungor** [comment]
latest version.

**Comment by arael** [comment]
Has this version ever worked on your installation? What is the moodle version?

**Comment by mesutgungor** [comment]
As i said in the first post  it was working for nearly 2 months perfectly Moodle version is 
Moodle 2.7+ (Build: 20140605)

**Comment by mesutgungor** [comment]
Hi arael when i trigger the notify task from commandline i get an  error "unknown course module ID" 
what can cause this ? i run the following commandline script.

php schedule_task.php --execute=\\block_notifications\\task\\notify 

--> Processing course: 6AB-Social Studies
--> Processing course: 6AB-Hebrew... used 938 dbqueries
... used 0.58937096595764 seconds
Task failed: Unknown course Module ID

When i delete the notification block in the last course(6AB-Hebrew) it goes on and when it hits something that i don't know in a course it again failed.

**Comment by mesutgungor** [comment]
i go further  little more about the error log when i go to the course logs i see the following error issue
when the event context is other the detail log shows the same error. So the plugin should handle this situation like this. When checking the updates of a course, if the course has an event with the type "other" plugin should skip this event. How can we implement this in the plugin ?

**Comment by mesutgungor** [comment]
Hi again arael
i see that this problem occurs when a resource is deleted in a course notification block stop working because of that course. i don't know why this problem arise but to solve this problem i want skip to inform user if a course module is deleted. I just want to inform  when a resource is added.

**Comment by arael** [comment]
I'm currently trying replicate and understand the issue. I'll let you know as soon as possible.

**Comment by arael** [comment]
Meanwhile you can just disable "Calendar event deleted" and "Course module deleted" events in the Notifications settings panel.

**Comment by arael** [comment]
I have pushed a new version. This one should fix the issue. Please test it and let me know.

**Comment by mesutgungor** [comment]
Hi areal i have install the new version and conduct several test cases that you can look at below
Create New Course 
Add notification block
Uncheck the delete course module notify
and try the below 

Add a resource  -> Notify is OK
Delete a resource -> Notify block continue to work but not notify because i have unchecked.
Add a resource again -> Notify is OK

Then i check the delete course module notify 
Delete a resource -> Notify block stops working for that course also for other courses.
Then i uncheck the delete course module from the setting 
Notify block still not working

I remove the notification block notification works for other courses.

Once in a course notify block stops working it effects all the courses and if you do not remove the notification block it does not work again.

**Comment by arael** [comment]
Everything works fine here. Are you sure the last version is running on your installation. At this point I have doubts that it might be a cache problem. Would you please try to empty the cache in your installation.

Also, are there any errors when you start the task from CLI?

**Comment by arael** [comment]
Closing for now. Please let me know if you have any additional info and I'll look into it.
