### ISSUE TITLE
Deprecated ?

### ISSUE THREAD

**Issue by nachoan** [arael/moodle_notifications_20#18]
Hi, 

Debuggin shows me this error:

core\event\content_viewed has been deprecated. Please extend base event or other relevant abstract class.

    line 32 of /lib/classes/event/content_viewed.php: call to debugging()
    line 92 of /lib/classes/component.php: call to include_once()
    line ? of unknownfile: call to core_component::classloader()
    line ? of unknownfile: call to spl_autoload_call()
    line 75 of /report/eventlist/classes/list_generator.php: call to method_exists()
    line 43 of /report/eventlist/classes/list_generator.php: call to report_eventlist_list_generator::get_core_events_list()
    line 36 of /blocks/notifications/settings.php: call to report_eventlist_list_generator::get_all_events_list()
    line 99 of /lib/classes/plugininfo/block.php: call to include()
    line 56 of /admin/settings/plugins.php: call to core\plugininfo\block->load_settings()
    line 6653 of /lib/adminlib.php: call to require()
    line 537 of /admin/index.php: call to admin_get_root()

core\event\course_module_instances_list_viewed has been deperecated. Please use core\event\course_module_instance_list_viewed instead

    line 43 of /lib/classes/event/course_module_instances_list_viewed.php: call to debugging()
    line 92 of /lib/classes/component.php: call to include_once()
    line ? of unknownfile: call to core_component::classloader()
    line ? of unknownfile: call to spl_autoload_call()
    line 75 of /report/eventlist/classes/list_generator.php: call to method_exists()
    line 43 of /report/eventlist/classes/list_generator.php: call to report_eventlist_list_generator::get_core_events_list()
    line 36 of /blocks/notifications/settings.php: call to report_eventlist_list_generator::get_all_events_list()
    line 99 of /lib/classes/plugininfo/block.php: call to include()
    line 56 of /admin/settings/plugins.php: call to core\plugininfo\block->load_settings()
    line 6653 of /lib/adminlib.php: call to require()
    line 537 of /admin/index.php: call to admin_get_root()

Using Moodle 2.7.7 and last version of notifications block.

**Comment by arael** [comment]
How did you get those warnings? I have the same moodle version and I don't get those warnings.

Anyway, the core\event\course_module_instances_list_viewed is not used by the block. It is not stored in the log table so it should not have any impact on the block.

/blocks/notifications/settings.php: call to report_eventlist_list_generator::get_all_events_list() >>> this call here is just to get the list of the events available on moodle platform.

You can see in the block settings which events are observed.

**Comment by arael** [comment]
Closing this issue for now. Please let me know if you have additional info and I'll look into it again.
