### ISSUE TITLE
DDL sql execution errors when upgrading from 2014040404 

### ISSUE THREAD

**Issue by ewallah** [arael/moodle_notifications_20#19]
Debug info: Unknown column 'time_created' in 'mdl_block_notifications_log'
ALTER TABLE mdl_block_notifications_log ADD other LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci AFTER time_created
Error code: ddlexecuteerror

Debug info: Unknown column 'folder_updated' in 'mdl_block_notifications_courses'
ALTER TABLE mdl_block_notifications_courses ADD discussion_created TINYINT(1) NOT NULL DEFAULT 1 AFTER folder_updated
Error code: ddlexecuteerror

When upgrading from 2014040404	to 2015052800

**Comment by nadavkav** [comment]
Same here. While upgrading from 2012022901 to 2015052800 (while upgrading Moodle 2.4 to 2.8)

**Comment by nadavkav** [comment]
Just read the upgrade.txt to version 2.0. oups. I guess I did not remove the old block before upgrading. (Hope I can automate this, since I have several servers that needs upgrading)

**Comment by nadavkav** [comment]
Removing the old block and continuing with the upgrade works fine.
Thought, it would be nicer if the block upgrade.php script could remove the block instead of me dropping the tables using phpmyadmin.
