### ISSUE TITLE
'Error reading from database'

### ISSUE THREAD

**Issue by jojoob** [arael/moodle_notifications_20#20]
I've installed the latest version (2015052800) from github under Moodle 2.9. When executing the cron task I got the error message `Task failed: Error reading from database`. After troubleshooting I found out the error was produced by the SQL query executed in https://github.com/arael/moodle_notifications_20/blob/master/classes/Course.php#L384: `invalid input syntax for integer: "pending"`

I changed pending to 0 but however no notifications are send. The return result of the query is empty...

**Comment by arael** [comment]
I have tested the last version on the Moodle 2.9 and it seems to me that everything is working fine. Have you solved this problem? Any additional info on how can replicate the bug?

**Comment by jojoob** [comment]
Just tested again with Moodle 2.9.0 and head of master branch of this plugin.
Cron task fails:

```
****** notifications :: begin ******

Number of courses using the block: 1
--> Processing course: Test Course 1... used 25 dbqueries
... used 0.031059980392456 seconds
Scheduled task failed: Block Notifications Task,Error reading from database
```

I'm using PostgreSQL version 9.3+154
