### ISSUE TITLE
Docs: tell us that changes by admins don't notify

### ISSUE THREAD

**Issue by mwithheld** [arael/moodle_notifications_20#21]
Changes made by administrators don't result in email notifications, but this is not in the docs.  Can you please add it?

**Comment by mwithheld** [comment]
Maybe this should be a config item (global + per-course).

**Comment by arael** [comment]
I have updated the Readme file. The plugin uses a new logging mechanism and there are a lot of entries set as administrator level activities. All the admin activities are considered maintenance and are not reported by the block.
