### ISSUE TITLE
The RSS format is invalid with special characters

### ISSUE THREAD

**Issue by leblangi** [arael/moodle_notifications_20#22]
To reproduce:
- Switch to a lang with special characters (Ex. French)
- Install the block and configure it to use RSS Feeds
- As a teacher, generate some event
- If the course title, the event description or anything have a special caracter, the RSS Feed will be invalid

After verification, this is the method htmlentities() used in the method standardize() used in the plugin who cause the problem. In french, for exemple, the "é" char is replaced by "&eacute;" and the & char is disallowed in RSS Feed. See the message in the w3c validor:
https://validator.w3.org/feed/check.cgi

```
Sorry
This feed does not validate.
    line 16, column 43: XML parsing error: <unknown>:16:43: undefined entity [help]
                    <description>Module de cours cr&eacute;&eacute;  on Tue, 18 Aug  ...
                                                   ^
In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendation.
    Your feed appears to be encoded as "UTF-8", but your server is reporting "US-ASCII" [help]
```

I suggest to keep the special char and use UTF-8 instead.

Thanks!

**Comment by arael** [comment]
Fixed some time ago. Forgot to close the issue. Sorry for the long delay.
