### ISSUE TITLE
cron fails in PHP 7.2

### ISSUE THREAD

**Issue by ndunand** [arael/moodle_notifications_20#29]
`****** notifications :: begin ******PHP Fatal error:  Cannot use Object as Object because 'Object' is a special class name in /.../blocks/notifications/classes/User.php on line 4
`

**Comment by arael** [comment]
Which version do you have?

This has been fixed in this commit: https://github.com/arael/moodle_notifications_20/commit/f3b7c775c7a23442d8bbeae7eb96c3c356b8c328

**Comment by ndunand** [comment]
My bad we're on an old version because we're on Moodle 3.6, and as https://moodle.org/plugins/pluginversions.php?plugin=block_notifications doesn't officially support Moodle 3.6 it didn't get updated.

**Comment by arael** [comment]
Thank you for the notification. I have updated the plugin info in moodle.org. Now the moodle 3.6 is included.
